const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Anchor,
		C3.Behaviors.solid,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.LOS,
		C3.Plugins.Tilemap,
		C3.Plugins.Shape3D,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Particles,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.List,
		C3.Plugins.progressbar,
		C3.Behaviors.Turret,
		C3.Behaviors.Pin,
		C3.Behaviors.Fade,
		C3.Plugins.Multiplayer,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Acts.ScrollToBottom,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Multiplayer.Acts.SignallingConnect,
		C3.Plugins.Multiplayer.Acts.AddClientInputValue,
		C3.Plugins.Multiplayer.Acts.SyncObject,
		C3.Plugins.Multiplayer.Acts.SyncObjectInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Multiplayer.Cnds.OnSignallingConnected,
		C3.Plugins.Multiplayer.Acts.SignallingLogin,
		C3.Plugins.Multiplayer.Cnds.OnSignallingLoggedIn,
		C3.Plugins.Multiplayer.Exps.MyAlias,
		C3.Plugins.Multiplayer.Acts.SignallingJoinRoom,
		C3.Plugins.Multiplayer.Cnds.OnSignallingJoinedRoom,
		C3.Plugins.TextBox.Acts.SetReadOnly,
		C3.Plugins.TextBox.Acts.SetFocus,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.Multiplayer.Cnds.IsHost,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Multiplayer.Exps.MyID,
		C3.Plugins.Multiplayer.Acts.AssociateObjectWithPeer,
		C3.Plugins.List.Acts.AddItem,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Multiplayer.Cnds.OnSignallingLeftRoom,
		C3.Plugins.TextBox.Acts.SetEnabled,
		C3.Plugins.List.Acts.Clear,
		C3.Plugins.Multiplayer.Cnds.OnSignallingDisconnected,
		C3.Plugins.Multiplayer.Cnds.OnSignallingError,
		C3.Plugins.Multiplayer.Exps.ErrorMessage,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Multiplayer.Exps.PeerCount,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Acts.AddObstacle,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Pathfinding.Cnds.OnArrived,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.Multiplayer.Acts.SendPeerMessage,
		C3.Plugins.Multiplayer.Cnds.OnPeerMessage,
		C3.Plugins.Multiplayer.Exps.FromAlias,
		C3.Plugins.Multiplayer.Exps.Message,
		C3.Plugins.Multiplayer.Cnds.OnHostDisconnected,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Multiplayer.Exps.PeerID,
		C3.Plugins.Multiplayer.Acts.InputPredictObject,
		C3.Plugins.Multiplayer.Cnds.OnClientUpdate,
		C3.Plugins.System.Exps.setbit,
		C3.Plugins.Multiplayer.Acts.SetClientState,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.getbit,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Multiplayer.Acts.HostBroadcastMessage,
		C3.Plugins.Multiplayer.Exps.FromID,
		C3.Plugins.Multiplayer.Cnds.OnPeerConnected,
		C3.Plugins.Multiplayer.Cnds.ComparePeerCount,
		C3.Plugins.Multiplayer.Exps.PeerAlias,
		C3.Plugins.Multiplayer.Cnds.OnPeerDisconnected,
		C3.Plugins.List.Exps.ItemCount,
		C3.Plugins.List.Cnds.CompareTextAt,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.List.Acts.Remove,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Multiplayer.Exps.PeerState,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.TextBox.Cnds.IsVisible,
		C3.Plugins.Button.Cnds.IsVisible,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.progressbar.Acts.SetVisible,
		C3.Plugins.Multiplayer.Acts.SignallingDisconnect,
		C3.Plugins.System.Acts.SetLayoutEffectEnabled,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.List.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.LOS.Acts.AddObstacle,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Behaviors.MoveTo.Cnds.CompareSpeed,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.MoveTo.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.Turret.Acts.SetEnabled,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Cnds.IsEffectEnabled,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Plugins.Particles.Cnds.IsVisible,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Behaviors.Bullet.Acts.SetBounceOffSolids,
		C3.Behaviors.LOS.Acts.ClearObstacles,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Plugins.Multiplayer.Acts.DisconnectRoom,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.Button.Cnds.IsEnabled
	];
};
self.C3_JsPropNameTable = [
	{JoinButton: 0},
	{Title: 0},
	{NameTextBox: 0},
	{GameCodeBox: 0},
	{Tween: 0},
	{MoveTo: 0},
	{room: 0},
	{sky: 0},
	{scale: 0},
	{building: 0},
	{Logo: 0},
	{PressSpace: 0},
	{Anchor: 0},
	{HostIndicator: 0},
	{peerid: 0},
	{inputs: 0},
	{animation: 0},
	{Chat: 0},
	{Health: 0},
	{PlayerType: 0},
	{Player: 0},
	{Key: 0},
	{BulletAngle: 0},
	{Solid: 0},
	{BoundToLayout: 0},
	{ScrollTo: 0},
	{"8Direction": 0},
	{LineOfSight: 0},
	{Peer: 0},
	{Tilemap: 0},
	{Obstacles: 0},
	{Pathfinding: 0},
	{NPC: 0},
	{Layout_Reference: 0},
	{Obstacles2: 0},
	{Obstacles3: 0},
	{Obstacles4: 0},
	{IdleNPC: 0},
	{Enemies: 0},
	{Portal: 0},
	{Portal2: 0},
	{Portal3: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{PeerBullet: 0},
	{ChatLog: 0},
	{ChatTextBox: 0},
	{PeerList: 0},
	{SendButton: 0},
	{Label: 0},
	{Title2: 0},
	{ChatButton: 0},
	{LeaveChatButton: 0},
	{GameOverScreen: 0},
	{HealthBar: 0},
	{MainMenuButton: 0},
	{RestartButton: 0},
	{Turret: 0},
	{Boss: 0},
	{Pin: 0},
	{BossFire: 0},
	{FireBullet: 0},
	{Fade: 0},
	{Fire: 0},
	{TurretBullet: 0},
	{"3DShape": 0},
	{BossHealthBar: 0},
	{PressurePlate: 0},
	{PressurePlate2: 0},
	{Lock: 0},
	{Block: 0},
	{Door: 0},
	{Door2: 0},
	{Door3: 0},
	{Door4: 0},
	{PressurePlate3: 0},
	{PressurePlate4: 0},
	{PressurePlate5: 0},
	{Block2: 0},
	{Block3: 0},
	{Block4: 0},
	{Block5: 0},
	{Door5: 0},
	{Block6: 0},
	{Block7: 0},
	{Block8: 0},
	{Block9: 0},
	{Block10: 0},
	{Door6: 0},
	{PressurePlate6: 0},
	{Door7: 0},
	{Door8: 0},
	{Door9: 0},
	{Door10: 0},
	{PressurePlate7: 0},
	{Door11: 0},
	{Block11: 0},
	{Block12: 0},
	{Block13: 0},
	{Block14: 0},
	{PressurePlate8: 0},
	{PressurePlate9: 0},
	{PressurePlate10: 0},
	{CreditsTitle: 0},
	{ArtistsCredits: 0},
	{AudioCredits: 0},
	{GameEngineCredits: 0},
	{LicencedAssetsCredits: 0},
	{ProgrammersCredits: 0},
	{ArtistsCredits2: 0},
	{ProgrammersCredits2: 0},
	{AudioCredits2: 0},
	{GameEngineCredits2: 0},
	{LicencedAssetsCredits2: 0},
	{CreditsTitle2: 0},
	{Credits: 0},
	{CreditsControlText: 0},
	{Multiplayer: 0},
	{Keyboard: 0},
	{Audio: 0},
	{GAME_NAME: 0},
	{INSTANCE_NAME: 0},
	{message: 0},
	{MyUsername: 0},
	{GameCode: 0}
];

self.InstanceType = {
	JoinButton: class extends self.IButtonInstance {},
	Title: class extends self.ITextInstance {},
	NameTextBox: class extends self.ITextInputInstance {},
	GameCodeBox: class extends self.ITextInputInstance {},
	room: class extends self.ISpriteInstance {},
	sky: class extends self.ISpriteInstance {},
	building: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	PressSpace: class extends self.ITextInstance {},
	HostIndicator: class extends self.ITextInstance {},
	Peer: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Obstacles: class extends self.I3DShapeInstance {},
	NPC: class extends self.ISpriteInstance {},
	Layout_Reference: class extends self.ISpriteInstance {},
	Obstacles2: class extends self.I3DShapeInstance {},
	Obstacles3: class extends self.I3DShapeInstance {},
	Obstacles4: class extends self.I3DShapeInstance {},
	IdleNPC: class extends self.ISpriteInstance {},
	Enemies: class extends self.ISpriteInstance {},
	Portal: class extends self.IParticlesInstance {},
	Portal2: class extends self.IParticlesInstance {},
	Portal3: class extends self.IParticlesInstance {},
	PeerBullet: class extends self.ISpriteInstance {},
	ChatLog: class extends self.ITextInputInstance {},
	ChatTextBox: class extends self.ITextInputInstance {},
	PeerList: class extends self.IListInstance {},
	SendButton: class extends self.IButtonInstance {},
	Label: class extends self.ITextInstance {},
	Title2: class extends self.ITextInstance {},
	ChatButton: class extends self.IButtonInstance {},
	LeaveChatButton: class extends self.IButtonInstance {},
	GameOverScreen: class extends self.ISpriteInstance {},
	HealthBar: class extends self.IProgressBarInstance {},
	MainMenuButton: class extends self.IButtonInstance {},
	RestartButton: class extends self.IButtonInstance {},
	Boss: class extends self.ISpriteInstance {},
	BossFire: class extends self.IParticlesInstance {},
	FireBullet: class extends self.ISpriteInstance {},
	Fire: class extends self.IParticlesInstance {},
	TurretBullet: class extends self.ISpriteInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	Turret: class extends self.ISpriteInstance {},
	BossHealthBar: class extends self.IProgressBarInstance {},
	PressurePlate: class extends self.ISpriteInstance {},
	PressurePlate2: class extends self.ISpriteInstance {},
	Block: class extends self.I3DShapeInstance {},
	Door: class extends self.I3DShapeInstance {},
	Door2: class extends self.I3DShapeInstance {},
	Door3: class extends self.I3DShapeInstance {},
	Door4: class extends self.I3DShapeInstance {},
	PressurePlate3: class extends self.ISpriteInstance {},
	PressurePlate4: class extends self.ISpriteInstance {},
	PressurePlate5: class extends self.ISpriteInstance {},
	Block2: class extends self.I3DShapeInstance {},
	Block3: class extends self.I3DShapeInstance {},
	Block4: class extends self.I3DShapeInstance {},
	Block5: class extends self.I3DShapeInstance {},
	Door5: class extends self.I3DShapeInstance {},
	Block6: class extends self.I3DShapeInstance {},
	Block7: class extends self.I3DShapeInstance {},
	Block8: class extends self.I3DShapeInstance {},
	Block9: class extends self.I3DShapeInstance {},
	Block10: class extends self.I3DShapeInstance {},
	Door6: class extends self.I3DShapeInstance {},
	PressurePlate6: class extends self.ISpriteInstance {},
	Door7: class extends self.I3DShapeInstance {},
	Door8: class extends self.I3DShapeInstance {},
	Door9: class extends self.I3DShapeInstance {},
	Door10: class extends self.I3DShapeInstance {},
	PressurePlate7: class extends self.ISpriteInstance {},
	Door11: class extends self.I3DShapeInstance {},
	Block11: class extends self.I3DShapeInstance {},
	Block12: class extends self.I3DShapeInstance {},
	Block13: class extends self.I3DShapeInstance {},
	Block14: class extends self.I3DShapeInstance {},
	PressurePlate8: class extends self.ISpriteInstance {},
	PressurePlate9: class extends self.ISpriteInstance {},
	PressurePlate10: class extends self.ISpriteInstance {},
	CreditsTitle: class extends self.ITextInstance {},
	ArtistsCredits: class extends self.ITextInstance {},
	AudioCredits: class extends self.ITextInstance {},
	GameEngineCredits: class extends self.ITextInstance {},
	LicencedAssetsCredits: class extends self.ITextInstance {},
	ProgrammersCredits: class extends self.ITextInstance {},
	ArtistsCredits2: class extends self.ITextInstance {},
	ProgrammersCredits2: class extends self.ITextInstance {},
	AudioCredits2: class extends self.ITextInstance {},
	GameEngineCredits2: class extends self.ITextInstance {},
	LicencedAssetsCredits2: class extends self.ITextInstance {},
	CreditsTitle2: class extends self.ITextInstance {},
	Credits: class extends self.ISpriteInstance {},
	CreditsControlText: class extends self.ITextInstance {},
	Multiplayer: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {}
}